# wrangler.toml â€“ lets Pages know where your OpenNext assets are and provides a compat date
name = "stickypicky"
compatibility_date = "2024-12-01"

# This is key for Cloudflare Pages:
pages_build_output_dir = ".open-next/assets"
