name = "stickypicky"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

# ðŸ‘‡ Pages Functions bindings
[[kv_namespaces]]
binding = "BADGE_KV"
id = "3419377f0cf64944bcf9e4c8c81dce33"
preview_id = "7995954175aa452285a4676d66ddda82"
